### ISSUE TITLE
Do not show Swift card number to Swift on Mobile users; instead show SoMTicketNumber

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-refund#101]
Fixes ISRN problem (ISRN does not show unless the ticket is active in Google Pay) the easiest way.

I duplicated the TicketNumber field (pull request is in), but the logic needs adding so that people who select Swift on Mobile on the first screen gets shown the SoMTicketNumber field.

**Comment by daylesalmon** [comment]
Fixed in: #102
