### ISSUE TITLE
Form not loading for people on WMCA network laptops

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-refund#125]
Had lots of reports from Ticketing & Customer Services that the form does not load on Chrome or Edge.

> "That's because of the CDN issue...I can change to the backup one Paul gave tomo"

**Comment by daylesalmon** [comment]
I believe I fixed this last night, I need someone with a WMCA laptop to confirm what the issue was.

**Comment by daylesalmon** [comment]
Confirmed as working by Warren.
