### ISSUE TITLE
Paper Ticket > Corporate > Cancel

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-refund#128]
For some reason, the form accepts the user's photo (under 4MB and within types) on step 3, but then provides an Error when the user tries to submit the application. Error 400, no clear reason why in dev tools.

We screenshotted the photo and then it worked.

![proofcorp](https://user-images.githubusercontent.com/10854265/79217808-590ca480-7e47-11ea-96cb-2c31db56f067.jpg)

<img width="594" alt="Screenshot 2020-04-14 at 11 47 46" src="https://user-images.githubusercontent.com/10854265/79217814-5d38c200-7e47-11ea-958e-dc964d51f2c2.png">

**Comment by thegreatgulper** [comment]
I can not really spot anything wrong with the upload. From your description, it seems like validation on the client-side does not much the validation on the backend. The' bad request' indicates that backend receives malformed or wrong data.

**Comment by daylesalmon** [comment]
Closing, as this was an issue with Paul's API looking for file sizes of 3MB and not 4MB.
This has now been fixed via the API.
