### ISSUE TITLE
Refund Form issues on IE11 

### ISSUE THREAD

**Issue by KaterinaKir** [wmcadigital/wmn-refund#132]
Users are reporting issues on Internet Explorer browsers. We aim to support IE11 only. Please test the refund form and fix any outstanding bugs. Below is some user feedback:

'Doesnt work in Internet Explorer, it lets you enter all your details and then doesn't submit'
'Internet explorer did not respond/complete once application sent.'

**Comment by daylesalmon** [comment]
This has been fixed in PR #134
