### ISSUE TITLE
Despite clearing cache multiple times, spacing still strange between questions and fields in Safari

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-refund#22]
<img width="1649" alt="Screenshot 2020-04-01 at 19 00 32" src="https://user-images.githubusercontent.com/10854265/78170598-13190f00-744b-11ea-8a8b-77d8a7963550.png">

**Comment by mrmjprice** [comment]
Tried on my iPad and iPhone and happening in safari there too 🙃

**Comment by daylesalmon** [comment]
Is this still happening?

**Comment by daylesalmon** [comment]
This has been fixed via: https://github.com/wmcadigital/wmn-design-system/commit/e1e7e11321001cfaab3c5d802a296b9658abb88a
