### ISSUE TITLE
Backlog: Summary page

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-refund#60]
For form iteration / post-form release

watch analytics and see how many forms were incorrect.

**Comment by daylesalmon** [comment]
https://analytics.google.com/analytics/web/#/report/content-event-pages/a3407557w13499218p84257006/explorer-table.plotKeys=%5B%5D&explorer-segmentExplorer.segmentId=analytics.eventCategory&_r.drilldown=analytics.pageTitle:Apply%20for%20a%20ticket%20refund%20due%20to%20Coronavirus%20(COVID-19)%20-%20West%20Midlands%20Network

**Comment by daylesalmon** [comment]
[Analytics All Data Event Pages 20200401-20200420 (1).pdf](https://github.com/wmcadigital/wmn-refund/files/4514672/Analytics.All.Data.Event.Pages.20200401-20200420.1.pdf)
[Analytics All Data Event Pages 20200401-20200420.pdf](https://github.com/wmcadigital/wmn-refund/files/4514675/Analytics.All.Data.Event.Pages.20200401-20200420.pdf)
